uuid = "073e85d6-52e1-41cd-94ac-d16046147dda"
name = "Auto Romanizer"
version = "1.0.0"
authors = ['SPbot']
description = "Romaniza automáticamente títulos, artistas y álbumes de japonés a Romaji preservando metadatos originales."
categories = ['metadata', 'ui']
homepage = "https://github.com/devil1210/picard-auto-romanizer"
report_bugs_to = "https://github.com/devil1210/picard-auto-romanizer"
api = ["3.0"]
license = "GPL-2.0-or-later"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
